-- Migration 032: Phase 4 Index Optimization
-- Drop redundant/duplicate indexes and add missing critical indexes
-- Generated by querying pg_index for duplicate (table, columns) pairs

BEGIN;

-- ============================================================
-- PART 1: Drop redundant duplicate indexes
-- Rule: keep UNIQUE index over non-unique; if both non-unique, keep shorter name
-- ============================================================

-- billing_records: both non-unique on (org_id, agent_name) — keep shorter name
DROP INDEX IF EXISTS idx_billing_records_org_agent;

-- conversation_analytics: unique constraint wins over plain index on (session_id)
DROP INDEX IF EXISTS idx_conv_analytics_session;

-- custom_domains: unique constraint wins over plain index on (hostname)
DROP INDEX IF EXISTS idx_custom_domains_hostname;

-- dlp_agent_policies: unique constraint wins over plain index on (org_id, agent_name)
DROP INDEX IF EXISTS idx_dlp_agent_policies_agent;

-- gpu_endpoints: unique constraint wins over plain index on (endpoint_id)
DROP INDEX IF EXISTS idx_gpu_endpoint_id;

-- orgs: unique constraint wins over plain index on (slug)
DROP INDEX IF EXISTS idx_orgs_slug;

-- skills: unique constraint wins over plain index on (org_id, name)
DROP INDEX IF EXISTS idx_skills_org_name;

-- training_iterations: unique constraint wins over plain index on (job_id, iteration_number)
DROP INDEX IF EXISTS idx_training_iterations_job;

-- users: unique constraint wins over plain index on (email)
DROP INDEX IF EXISTS idx_users_email;

-- voice_numbers: unique constraint wins over plain index on (phone_number)
DROP INDEX IF EXISTS idx_voice_numbers_phone;

-- api_keys: non-unique idx_api_keys_hash redundant after creating unique idx_api_keys_key_hash
DROP INDEX IF EXISTS idx_api_keys_hash;

-- sessions: full index on trace_id redundant — partial index (WHERE NOT NULL) covers all queries
DROP INDEX IF EXISTS idx_sessions_trace_id;

-- NOTE: Skipped evolution_proposals (idx_evolution_proposals_applied vs idx_evolution_proposals_agent_status)
--   These have different WHERE clauses — the partial index is not redundant.
-- NOTE: Skipped turns (idx_turns_refusal vs idx_turns_created)
--   idx_turns_refusal has WHERE (refusal = true) — a useful partial index, not a duplicate.

-- ============================================================
-- PART 2: Add missing critical indexes
-- ============================================================

-- Auth hot path: API key lookup on every request
CREATE UNIQUE INDEX IF NOT EXISTS idx_api_keys_key_hash
  ON api_keys(key_hash);

-- Auth hot path: active (non-revoked) user session lookup
CREATE INDEX IF NOT EXISTS idx_user_sessions_active
  ON user_sessions(user_id)
  WHERE revoked = false;

-- Session queries: trace correlation
CREATE INDEX IF NOT EXISTS idx_sessions_trace
  ON sessions(trace_id)
  WHERE trace_id IS NOT NULL;

-- Session queries: dashboard listing by org + time
CREATE INDEX IF NOT EXISTS idx_sessions_org_created
  ON sessions(org_id, created_at DESC);

-- Session queries: dashboard listing by org + agent + time
CREATE INDEX IF NOT EXISTS idx_sessions_org_agent_created
  ON sessions(org_id, agent_name, created_at DESC);

-- Billing: trace correlation for cost attribution
CREATE INDEX IF NOT EXISTS idx_billing_records_trace
  ON billing_records(trace_id)
  WHERE trace_id IS NOT NULL;

-- Session feedback: lookup by session
CREATE INDEX IF NOT EXISTS idx_session_feedback_session
  ON session_feedback(session_id);

-- Missing FK indexes: marketplace_featured → listing
CREATE INDEX IF NOT EXISTS idx_marketplace_featured_listing
  ON marketplace_featured(listing_id);

-- Missing FK indexes: subgraph_definitions → component
CREATE INDEX IF NOT EXISTS idx_subgraph_defs_component
  ON subgraph_definitions(component_id);

COMMIT;
